model_name: 'swin_tiny_patch4_window7_224.ms_in1k'
workers: 16
image_size: 224
batch_size: 384
init_lr: 0.0001
epochs: 30
mixup: True
ema: True
ema_decay: 0.995
use_ext_data: True
downsampling: True
downsampling_type: 'type2'
neg_pos_ratio: 3
patience: 5
ema_saved_epoch: 8