model_name: 'swinv2_tiny_window8_256.ms_in1k'
workers: 16
image_size: 256
batch_size: 256
init_lr: 0.0001
epochs: 30
mixup: True
ema: True
ema_decay: 0.995
downsampling_type: 'type2'
neg_pos_ratio: 50
patience: 10
ema_saved_epoch: 7